#!/bin/bash

set -euo pipefail

# Setup github cli packages
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
sudo apt-get update

echo "Installing apt packages"
sudo apt-get -y install \
	gh \
	python3-pip \
	cargo

# echo "Installing lastversion"
# pip3 install lastversion

if [ ! -d /usr/local/bin ]; then
	sudo mkdir -p /usr/local/bin
fi

echo "Installing exa"
cargo install exa
mv "${HOME}"/.cargo/exa /usr/local/bin/exa
