#!/usr/bin/env bash

set -euo pipefail

DEFAULT_CONFIG_PREFIX="install"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule sync --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive

shopt -s nullglob
plugin_dirs=(plugins/*)
shopt -u nullglob

plugins=()
for plugin_dir in ${plugin_dirs[@]}; do
  plugins+=("--plugin-dir" ${plugin_dir})
done

for conf in ${DEFAULT_CONFIG_PREFIX}; do
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    "${plugins[@]}" \
    -c "${conf}${CONFIG_SUFFIX}" "${@}"
done
