## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
gh.pkg-path = "gh"
eza.pkg-path = "eza"
fd.pkg-path = "fd"
ripgrep.pkg-path = "ripgrep"
neovim.pkg-path = "neovim"
zoxide.pkg-path = "zoxide"
starship.pkg-path = "starship"
direnv.pkg-path = "direnv"
tree-sitter.pkg-path = "tree-sitter"
nodejs.pkg-path = "nodejs"
ruby.pkg-path = "ruby"
fzf.pkg-path = "fzf"
lazygit.pkg-path = "lazygit"
git.pkg-path = "git"

bat.pkg-path = "bat"
entr.pkg-path = "entr"
delta.pkg-path = "delta"
batman.pkg-path = "bat-extras.batman"
batdiff.pkg-path = "bat-extras.batdiff"
batgrep.pkg-path = "bat-extras.batgrep"
batpipe.pkg-path = "bat-extras.batpipe"
batwatch.pkg-path = "bat-extras.batwatch"
prettybat.pkg-path = "bat-extras.prettybat"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
# on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
# '''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
# Uncomment to disable CUDA detection.
# cuda-detection = false
