#!/usr/bin/env bash

set -euo pipefail

mkdir -p ~/.1password

if [ ! -L ~/.1password/agent.sock ]; then
  ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ~/.1password/agent.sock
fi
