#!/bin/bash

set -euo pipefail

OS="$(uname)"
if [[ "$OS" == "Linux" ]]; then
  suffix="linux"
else
  suffix="macos"
fi

case `grep -Fq ".gitconfig.${suffix}" ~/.gitconfig >/dev/null; echo $?` in
  0)
    #no-op
    ;;
  1)
    echo "Adding .gitconfig.${suffix} to .gitconfig"
    cat >>~/.gitconfig <<-EOM
[include]
  path = .gitconfig.${suffix}
EOM
    ;;
  *)
    echo "Failed to detect gitconfig!"
    exit 1
    ;;
esac
