#!/usr/bin/env bash

set -euo pipefail

selected_binary="${1:?Missing required argument: selected binary}"

dir=$(mktemp -d -t "install-manifest-tool.XXXXXX")
function cleanup {
  rm -rf "${dir}"
}
trap cleanup EXIT

cd "${dir}"

version=$(lastversion estesp/manifest-tool --having-asset)
echo "Found version ${version}"
curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v${version}/binaries-manifest-tool-${version}.tar.gz > binaries-manifest-tool.tar.gz

tar -xf binaries-manifest-tool.tar.gz

cp -f "${selected_binary}" ~/.local/bin/manifest-tool
chmod +x ~/.local/bin/manifest-tool
