#!/bin/bash

set -euo pipefail

# Install goss
curl -L https://github.com/goss-org/goss/releases/latest/download/goss-linux-amd64 -o ~/.local/bin/goss-linux-amd64
chmod +rx ~/.local/bin/goss-linux-amd64

curl -L https://github.com/goss-org/goss/releases/latest/download/goss-linux-arm64 -o ~/.local/bin/goss-linux-arm64
chmod +rx ~/.local/bin/goss-linux-arm64

# Install dgoss
curl -L https://raw.githubusercontent.com/goss-org/goss/master/extras/dgoss/dgoss -o ~/.local/bin/dgoss
chmod +rx ~/.local/bin/dgoss
