#!/usr/bin/env bash

set -euo pipefail

selected_binary="${1:?Missing required argument: selected binary}"

dir=$(mktemp -d -t "install-manifest-tool.XXXXXX")
function cleanup {
	rm -rf "${dir}"
}
trap cleanup EXIT

cd "${dir}"

download_url=$(curl -fsSL https://api.github.com/repos/estesp/manifest-tool/releases/latest | jq -r '.assets[] | select(.name | contains("binaries-manifest-tool") and contains("sha256sum") | not) | .browser_download_url')
echo "Downloading from $download_url"
curl -fsSL "${download_url}" >binaries-manifest-tool.tar.gz

tar -xf binaries-manifest-tool.tar.gz

cp -f "${selected_binary}" ~/.local/bin/manifest-tool
chmod +x ~/.local/bin/manifest-tool
